
FROM node:12.14.0-alpine as BASE

ARG environment
ENV environment=${environment}
ENV PORT=$PORT

WORKDIR /usr/src/app
COPY package.json ./
COPY .babelrc ./
COPY .dockerignore ./
RUN ls -a

# RUN apk update && apk upgrade && apk add --no-cache bash git openssh curl && \
RUN npm set progress=false && npm config set depth 0 && \
    # apk update && apk upgrade && apk add --no-cache bash git openssh curl && \
    npm i
COPY . .

RUN ls -a

FROM node:12.14.0-alpine as FINAL
WORKDIR /app
COPY .dockerignore ./
COPY --from=BASE /usr/src/app/ /app/

RUN ls -a

EXPOSE $PORT
CMD [ "npm", "run", "start:prod" ]
